FILE_EXTENSION = "{source}/{task}/{key}"
TRAIN_FILE = "./training-data/xtt_ranked.pkl"
GOLD_FILE = "./training-data/xtt_golds_no_ties.pkl"
ABLATIONS_PATH = "./resources/fine_categorization.csv"
RESULTS_PATH = "./results.tsv"