FILE_EXTENSION = "{source}/{task}/{arch}/{key}"
TRAIN_FILE = "./training-data/{arch}_{task}_ranked.pkl"
GOLD_FILE = "./training-data/{arch}_{task}_golds.pkl"
ABLATIONS_PATH = "./resources/fine_categorization.csv"
RESULTS_PATH = "./results.tsv"