FILE_EXTENSION = "{source}/{task}/{key}"
TRAIN_FILE = "./training-data/{task}_gram_ranked_train_no_ties.pkl"
GOLD_FILE = "./training-data/{task}_gram_golds_no_ties.pkl"
ABLATIONS_PATH = "./resources/fine_categorization.csv"
RESULTS_PATH = "./results.tsv"